"""add token tables (activation, password_reset, refresh)

Revision ID: e0928fde3a5b
Revises: 69a6be7e12f2
Create Date: 2026-07-03 20:05:43.406734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0928fde3a5b'
down_revision: Union[str, Sequence[str], None] = '69a6be7e12f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
